GTCEuStartupEvents.registry('gtceu:material', event => {

    event.create('pandora')
        .ore()
        .liquid()
        .gas()
        .color(0x9e7c61)
        .formula('Pn')
        .iconSet(GTMaterialIconSet.RUBY)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES, GTMaterialFlags.NO_ORE_PROCESSING_TAB)

    event.create('hyperium')
        .dust()
        .blastTemp(3700)
        .color(0xdce225)
        .formula('Hy')
        .iconSet(GTMaterialIconSet.DULL)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES, GTMaterialFlags.GENERATE_FOIL)

    event.create('maliwanium')
        .dust()
        .blastTemp(3700)
        .color(0xd9ab26)
        .formula('Mw')
        .iconSet(GTMaterialIconSet.FINE)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES, GTMaterialFlags.GENERATE_FOIL)

    event.create('eridium')
        .liquid()
        .dust()
        .blastTemp(3700)
        .color(0xa627d8)
        .formula('E')
        .iconSet(GTMaterialIconSet.SHINY)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES, GTMaterialFlags.GENERATE_FOIL)

    event.create('banditium')
        .dust()
        .color(0xe3ba1c)
        .formula('Bn')
        .iconSet(GTMaterialIconSet.SHINY)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('muddied_banditium')
        .dust()
        .color(0xa18414)
        .formula('Bn')
        .iconSet(GTMaterialIconSet.SHINY)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('corporium')
        .gas()
        .color(0x7b8480)
        .formula('Ci')
        .iconSet(GTMaterialIconSet.SHINY)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('elpisium')
        .dust()
        .gas()
        .color(0x9e5fa0)
        .formula('Em')
        .iconSet(GTMaterialIconSet.SHINY)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('jakobium')
        .dust()
        .color(0x6F4E37)
        .formula('Jk')
        .iconSet(GTMaterialIconSet.SHINY)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('eden_6')
        .gas()
        .dust()
        .color(0x988558)
        .formula('Ed-6')
        .iconSet(GTMaterialIconSet.SHINY)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('skagium')
        .gas()
        .dust()
        .color(0xC4A484)
        .formula('Skag!')
        .iconSet(GTMaterialIconSet.SHINY)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('rakkium')
        .gas()
        .color(0x8B4513)
        .formula('Rakk!')
        .iconSet(GTMaterialIconSet.SHINY)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('insanium')
        .ore()
        .color(0xfb1104)
        .formula('My chilli recipe dies with me!')
        .iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES, GTMaterialFlags.NO_ORE_PROCESSING_TAB)

    event.create('refined_insanium')
        .dust()
        .color(0xff001c)
        .formula('Lets agree to disagree!')
        .iconSet(GTMaterialIconSet.SHINY)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('puric_insanium')
        .fluid()
        .dust()
        .color(0xff003a)
        .formula('What does it all mean!?')
        .iconSet(GTMaterialIconSet.SHINY)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('molten_sanity')
        .liquid()
        .color(0x25da2c)
        .formula('?!?')
        .iconSet(GTMaterialIconSet.SHINY)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('handsomium')
        .liquid()
        .color(0x977368)
        .formula('HnDSmJ')
        .iconSet(GTMaterialIconSet.SHINY)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)
    //₀ ₁ ₂ ₃ ₄ ₅ ₆ ₇ ₈ ₉

})