Platform.mods.kubejs.name = 'Greg-E'

StartupEvents.registry('item', event => {

    //Add new items
    event.create('hammer', 'pickaxe').tier('stone').displayName('Small Hammer')
    event.create('insulation').displayName('Poorly-made Cable Insulation')
    event.create('ironshard').displayName('Iron Shards')
    event.create('tornconveyor').displayName('LV Torn Conveyor')
    event.create('rawcolor').displayName('Raw Color')
    event.create('manasteelfoil').displayName('Manasteel Foil')
    event.create('deepslateearth').displayName('Deepslate Earth')
    event.create('seniron').displayName('Sentient Ingot')
    event.create('senplate').displayName('Sentient Plate')
    event.create('senironspeck').displayName('Speck of Sentient Dust')
    event.create('senironsmpile').displayName('Small Pile of Sentient Dust')
    event.create('heatcoil').displayName('Heating Coil')
    event.create('supingot').displayName('Ultraconducting Alloy Ingot')
    event.create('supcables').displayName('Ultraconducting Alloy Wire')
    event.create('uncomp').displayName('Unknown Compound')
    event.create('hydraingot').displayName('Hydra Ingot')
    event.create('knightingot').displayName('Phantom Knight Ingot')
    event.create('mushroomingot').displayName('Minoshroom Ingot')
    event.create('lichingot').displayName('Lich Ingot')
    event.create('twilightingots').displayName('Twilight Alloy Ingot')
    event.create('twilightfoil').displayName('Twilight Alloy Foil')
    event.create('li').displayName('Lithium-6 Ampoule')
    event.create('pu').displayName('Plutonium Ampoule')
    event.create('cm').displayName('Curium Ampoule')
    event.create('he').displayName('Helium Ampoule')
    event.create('c').displayName('Carbon Ampoule')
    event.create('no').displayName('Nobelium Ampoule')
    event.create('voiddust').displayName('Void Dust')
    event.create('voidtent').displayName('Void Tentacle')
    event.create('voidgoo').displayName('Void Goo')
    event.create('voidegg').displayName('Void-touched Egg')
    event.create('voideggopen').displayName('Opened Void-touched Egg')
    event.create('voidorga').displayName('Void Organism')
    event.create('voidorgparts').displayName('Void Organism Parts')
    event.create('deshfoil').displayName('Desh Foil')
    event.create('voidhole').displayName('Void Wormhole')
    event.create('hmold').displayName('Gold Hammer Head Mold')
    event.create('hhead').displayName('Stone Hammer Head')
    event.create('fhhead').displayName('Franklinite Hammer Head Mold')
    event.create('fhammer').displayName('Franklinite Hammer')
    event.create('orichalcumpli').displayName('Orichalcum Pliers')
    event.create('dwpliblue').displayName('Dwarven Pliers Blueprint')
    event.create('dwppart').displayName('Dwarven Pliers Blueprint Part')
    event.create('orichalcum').displayName('Orichalcum Ingot')
    event.create('mixedin').displayName('Mixed Energy Ingot')
    event.create('cursedin').displayName('Cursed Energy Ingot')
    event.create('mythrilcoating').displayName('Mythril Coating')
    event.create('drahead').displayName('Corrupted Dragon Skull')
    event.create('cpottery').displayName('Curious Pottery Sherd')
    event.create('dewvial').displayName('Dew Vial')
    event.create('dwre').displayName('Dwarven Pottery Bundle')
    event.create('mybrush').displayName('Mythril Brush')
    event.create('vanaheimingot').displayName('Vanaheim Ingot')
    event.create('malachitefoil').displayName('Malachite Foil')
    event.create('clogwire').displayName('Pure Cloggrum Wire')
    event.create('frostwire').displayName('Pure Froststeel Wire')
    event.create('forgfoil').displayName('Forgotten Ingot Foil')
    event.create('eidust').displayName('Evil And Intimidating Dust')
    event.create('iceshard').displayName('Ice Shard')
    event.create('gassydust').displayName('Crystallized Gasses')
    event.create('evilsoul').displayName('Evil Soul')
    event.create('runeingot').displayName('Rune Ingot')
    event.create('bloodinfused').displayName('Blood Infused Ingot')
    event.create('activatedrune').displayName('Activated Ore Rune')
    event.create('rune').displayName('Ore Rune')
    event.create('witchlabflask').displayName('Witch’s Lab Flask')
    event.create('bacterialmatter').displayName('Bacterial Matter')
    event.create('bacterialmatteringot').displayName('Bacterial Matter Ingot')
    event.create('animated/draconicprocessor').displayName('Draconic Processor')
    event.create('learningchip').displayName('Learning Chip')
    event.create('dustwithbroom').displayName('Dust From Sampler')
    event.create('neutroniuminfused').displayName('Neutronium Infused Dust')
    event.create('pelletmold').displayName('Casting Mold (Pellet)')
    event.create('purecloggrum').displayName('Pure Cloggrum Ingot')
    event.create('purefroststeel').displayName('Pure Froststeel Ingot')
    event.create('hotfroststeel').displayName('Hot Froststeel Ingot')
    event.create('hotcloggrum').displayName('Hot Cloggrum Ingot')
    event.create('kaptonmirror').displayName('Kapton Mirror')
    event.create('earthlydust').displayName('Fine Ground Dust')
    event.create('vileheart').displayName('Vile Heart')
    event.create('demonicgascan').displayName('Demonic Gas Coating')
    event.create('magicalseed').displayName('Magical Seed')
    event.create('magicallaserlens').displayName('Magical Laser Lens')
    event.create('mellodiumscience').displayName('Mellodium Science Kit')
    event.create('lasermining').displayName('Laser Mining Tool')
    event.create('vanilla').displayName('Vanilla Pod')
    event.create('tooth').displayName('Troll Tooth')
    event.create('alkhalaclaw').displayName('Alkhala Claw')
    event.create('deleriancoin').displayName('Delerian Coin')
    event.create('draeneiwood').displayName('Draenei Wood Plank')
    event.create('scepterofsand').displayName('Scepter Of The Shifting Sands')
    event.create('robotarm').displayName('Quaorian Robot Arm')
    event.create('sensor').displayName('Dwarven Sensor')
    event.create('computation_matrix').displayName('Computation Matrix')
    event.create('niobiumcoating').displayName('Niobium Zenithium Coating')
    event.create('twilight_flame').displayName('Twilight Flame')
    event.create('essentia_filter').displayName('Essentia Filter')
    event.create('cc').displayName('cu5tm Coin')

    event.create('ultimatecapacitor').displayName('Ultimate SMD Capacitor')
    event.create('ultimatediode').displayName('Ultimate SMD Diode')
    event.create('ultimateinductor').displayName('Ultimate SMD Inductor')
    event.create('ultimateresistor').displayName('Ultimate SMD Resistor')
    event.create('ultimatetransistor').displayName('Ultimate SMD Transistor')

    event.create('luvpermit').displayName('LuV Crafting Blueprints')
    event.create('zpmpermit').displayName('ZPM Crafting Blueprints')
    event.create('uvpermit').displayName('UV Crafting Blueprints')
    event.create('uhvpermit').displayName('UHV Crafting Blueprints')

    event.create('naquadahfilter').displayName('Naquadah Filter')
    event.create('nebulonfilter').displayName('Nebulon-Alpha Filter')
    event.create('prismaliumfilter').displayName('Prismalium Filter')

    event.create('rawcalculationpress').displayName('Raw Calculation Press')
    event.create('rawengineeringpress').displayName('Raw Engineering Press')
    event.create('rawlogicpress').displayName('Raw Logic Press')
    event.create('rawsiliconpress').displayName('Raw Silicon Press')

    event.create('commonearth').displayName('Common Earth')
    event.create('quartzspeck').displayName('Speck of Nether Quartz')
    event.create('cquartzspeck').displayName('Speck of Certus Quartz Crystal')
    event.create('quartzspile').displayName('Small Pile of Nether Quartz')
    event.create('cquartzspile').displayName('Small Pile of Certus Quartz Crystal')
    event.create('gspeck').displayName('Speck of Gold Dust')
    event.create('gspile').displayName('Small Pile of Gold Dust')
    event.create('dshard').displayName('Diamond Shard')
    event.create('dcluster').displayName('Diamond Cluster')
    event.create('lapisspeck').displayName('Speck of Lapis Lazuli')
    event.create('lapisspile').displayName('Small Pile of Lapis Lazuli')

    event.create('orbit/mercury')
    event.create('orbit/venus')
    event.create('orbit/earth')
    event.create('orbit/mars')
    event.create('orbit/jupiter')
    event.create('orbit/saturn')
    event.create('orbit/uranus')
    event.create('orbit/neptune')

    event.create('tomes/withertoken').displayName('Wither Token')
    event.create('tomes/gaiatoken').displayName('Gaia Token')
    event.create('tomes/chaostoken').displayName('Chaos Guardian Token')
    event.create('tomes/enderdragontoken').displayName('Ender Dragon Token')

    event.create('waterone').displayName('Compressed Water')
    event.create('watertwo').displayName('2x Compressed Water')
    event.create('waterthree').displayName('3x Compressed Water')
    event.create('waterfour').displayName('4x Compressed Water')
    event.create('waterfive').displayName('5x Compressed Water')

    event.create('animated/guicomp').displayName('Guidance Computer T1')
    event.create('animated/guicomptwo').displayName('Guidance Computer T2')
    event.create('animated/guicompthree').displayName('Guidance Computer T3')
    event.create('animated/guicompfour').displayName('Guidance Computer T4')

    event.create('bacterias/simplebacteria1').displayName('Plague Strain');
    event.create('bacterias/simplebacteria2').displayName('Graveyard Bacillus');
    event.create('bacterias/simplebacteria3').displayName('Swamp Culture');
    event.create('bacterias/simplebacteria4').displayName('Blood Streptococcus');
    event.create('bacterias/simplebacteria5').displayName('Necrotic Bacteria');
    event.create('bacterias/simplebacteria6').displayName('Lunar Microbe');
    event.create('bacterias/simplebacteria7').displayName('Shadow Pathogen');
    event.create('bacterias/simplebacteria8').displayName('Acidic Slime');
    event.create('bacterias/simplebacteria9').displayName('Glowing Spore');
    event.create('bacterias/simplebacteria10').displayName('Alchemical Ferment');
    event.create('bacterias/simplebacteria11').displayName('Mutated Phage');
    event.create('bacterias/simplebacteria12').displayName('Crystalline Bacteria');
    event.create('bacterias/simplebacteria13').displayName('Progenitor Bacteria');

})