StartupEvents.registry('block', event => {

    event.create('slurry_squeezer')
        .displayName('Squeezer')
        .stoneSoundType()
        .hardness(2.0) 
        .resistance(1.0)
        .texture('up', 'kubejs:block/slurrypressertopbot')
        .texture('down', 'kubejs:block/slurrypressertopbot')
        .texture('north', 'kubejs:block/slurrypresserside')
        .texture('south', 'kubejs:block/slurrypresserside')
        .texture('west', 'kubejs:block/slurrypresserside')
        .texture('east', 'kubejs:block/slurrypresserside')

    event.create('heatingel')
        .displayName('Heating Element')
        .stoneSoundType()
        .hardness(2.0) 
        .resistance(1.0)
        .textureAll('kubejs:block/heatingel')

    event.create('cobbleone')
        .displayName('Compressed Cobblestone')
        .stoneSoundType()
        .hardness(2.0) 
        .resistance(1.0)
        .textureAll('kubejs:block/cobbleone')
    
    event.create('cobbletwo')
        .displayName('2x Compressed Cobblestone')
        .stoneSoundType()
        .hardness(2.0) 
        .resistance(1.0)
        .textureAll('kubejs:block/cobbletwo')

    event.create('cobblethree')
        .displayName('3x Compressed Cobblestone')
        .stoneSoundType()
        .hardness(2.0) 
        .resistance(1.0)
        .textureAll('kubejs:block/cobblethree')
    
    event.create('cobblefour')
        .displayName('4x Compressed Cobblestone')
        .stoneSoundType()
        .hardness(2.0) 
        .resistance(1.0)
        .textureAll('kubejs:block/cobblefour')

    event.create('cobblefive')
        .displayName('5x Compressed Cobblestone')
        .stoneSoundType()
        .hardness(2.0) 
        .resistance(1.0)
        .textureAll('kubejs:block/cobblefive')

    event.create('researchlens')
        .displayName('Research Lens')
        .stoneSoundType()
        .hardness(2.0) 
        .resistance(1.0)
        .textureAll('kubejs:block/sprinklertopbot')
        .texture('down', 'kubejs:block/lensdown')
        
    event.create('laservoid')
        .displayName('Void Mining Laser')
        .stoneSoundType()
        .hardness(2.0) 
        .resistance(1.0)
        .textureAll('kubejs:block/sprinklertopbot')
        .texture('down', 'kubejs:block/laserdown')

    event.create('voidseed')
        .displayName('Void Seed')
        .stoneSoundType()
        .hardness(2.0) 
        .resistance(1.0)
        .textureAll('kubejs:block/voidseed')

    event.create('vanaheimingotblock')
        .displayName('Vanaheim Ingot Block')
        .stoneSoundType()
        .hardness(2.0) 
        .resistance(1.0)
        .textureAll('kubejs:block/vanaheim')

    event.create('solidacidinfusedlava')
        .displayName('Solid Acid-Infused Lava')
        .stoneSoundType()
        .hardness(2.0) 
        .resistance(1.0)
        .textureAll('kubejs:block/crystacidlava')

    event.create('vending_machine')
        .box(0, 0, 0, 16, 32, 16, true)
        .model('kubejs:block/vending')
        .displayName('Vending Machine')
        .stoneSoundType()
        .hardness(2.0) 
        .resistance(1.0)
        .fullBlock(false)
        
})