GTCEuStartupEvents.registry('gtceu:material', event => {

    event.create('cygnium')
        .fluid()
        .formula("Cy61")
        .color(0x2a54d5)
        .iconSet(GTMaterialIconSet.FINE)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('struvium')
        .fluid()
        .formula("Su2398")
        .color(0xa66759)
        .iconSet(GTMaterialIconSet.FINE)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('mellodium')
        .fluid()
        .dust()
        .blastTemp(3700)
        .formula("Ml")
        .color(0x3d27d8)
        .iconSet(GTMaterialIconSet.FINE)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_FOIL)

    event.create('lacallium')
        .fluid()
        .formula("L8760")
        .color(0xbeef10)
        .iconSet(GTMaterialIconSet.FINE)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('gliesium')
        .fluid()
        .formula("Gl1")
        .color(0x33113b)
        .iconSet(GTMaterialIconSet.FINE)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('prismalium')
        .fluid()
        .dust()
        .blastTemp(3700)
        .formula("Pr")
        .color(0x2ac9d5)
        .iconSet(GTMaterialIconSet.FINE)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_FOIL)

    event.create('ophiuchium')
        .fluid()
        .formula("Oh70")
        .color(0x37c857)
        .iconSet(GTMaterialIconSet.FINE)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('steinium')
        .fluid()
        .formula("Se2051")
        .color(0x5b2d0a)
        .iconSet(GTMaterialIconSet.FINE)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('stellarium')
        .fluid()
        .dust()
        .blastTemp(3700)
        .formula("Pr")
        .color(0xbdc4c3)
        .iconSet(GTMaterialIconSet.FINE)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_FOIL)

    event.create('astrophage_fuel')
        .fluid()
        .formula("As")
        .color(0xe9f40b)
        .iconSet(GTMaterialIconSet.FINE)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('activated_astrophage_fuel')
        .gas()
        .formula("As+++")
        .color(0xf4fa86)
        .iconSet(GTMaterialIconSet.FINE)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)


})