GTCEuStartupEvents.registry('gtceu:material', event => {

    event.create('nebulon_omega')
        .liquid()
        .ore()
        .formula("Nl-Ω")
        .iconSet(GTMaterialIconSet.FINE)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES, GTMaterialFlags.NO_ORE_PROCESSING_TAB)
        .color(0x702963)

    event.create('nebulon_gamma_slurry')
        .fluid()
        .formula("NqNl-γ")
        .color(0x702963)
        .iconSet(GTMaterialIconSet.ROUGH)

    event.create('nebulon_omega_dissolved')
        .fluid()
        .formula("2Na[(Nl-Ω)(OH)₄] + 3H₂")
        .color(0x702963)
        .iconSet(GTMaterialIconSet.ROUGH)

    event.create('naquadron_delta')
        .liquid()
        .plasma()
        .formula("NqNl-δ")
        .color(0x353935)
        .iconSet(GTMaterialIconSet.ROUGH)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('naquadron_zeta')
        .liquid()
        .formula("NqNl₂-ζ")
        .color(0x353935)
        .iconSet(GTMaterialIconSet.ROUGH)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('dinebulon_zeta')
        .liquid()
        .formula("Nl₂-ζ")
        .color(0x353935)
        .iconSet(GTMaterialIconSet.ROUGH)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('fluoronaquadic_acid')
        .liquid()
        .formula("H₂F₄Nq")
        .color(0x353935)
        .iconSet(GTMaterialIconSet.ROUGH)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('excited_naquadic_solution')
        .liquid()
        .formula("aq · (NqHF₂)!")
        .color(0x28282B)
        .iconSet(GTMaterialIconSet.ROUGH)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('dinebulon_zeta_omni_fluid')
        .liquid()
        .formula("(Nl₂-ζ) + (NqHF₂)")
        .color(0x28282B)
        .iconSet(GTMaterialIconSet.ROUGH)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('nebulon_zeta')
        .liquid()
        .formula("Nl-ζ")
        .color(0x28282B)
        .iconSet(GTMaterialIconSet.ROUGH)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('nebulon_gamma')
        .fluid()
        .formula("Nl-γ")
        .color(0x702963)
        .iconSet(GTMaterialIconSet.ROUGH)

    event.create('nebulon_alpha')
        .ingot()
        .liquid()
        .formula("Nl-α")
        .iconSet(GTMaterialIconSet.FINE)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_RING, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_LONG_ROD, GTMaterialFlags.GENERATE_ROUND, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_DENSE)
        .color(0x702963)

    event.create('p_xylene')
        .dust()
        .formula("C₈H₁₀")
        .color(0xF9F6EE)
        .iconSet(GTMaterialIconSet.ROUGH)
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('tetramethylbenzene')
        .fluid()
        .formula("C₆H₂(CH₃)₄")
        .color(0xFFFFF0)
        .iconSet(GTMaterialIconSet.ROUGH) 
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('vanadium_oxide')
        .gas()
        .formula("V₂O₅")
        .color(0xCC5500)
        .iconSet(GTMaterialIconSet.ROUGH) 
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('pmda')
        .gas()
        .formula("C₁₀H₂O₆")
        .color(0xFCF5E5)
        .iconSet(GTMaterialIconSet.ROUGH) 
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('diphenyl_ether')
        .gas()
        .formula("C₁₂H₁₀O")
        .color(0xFAF9F6)
        .iconSet(GTMaterialIconSet.ROUGH) 
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('dinitrodiphenyl_ether')
        .gas()
        .formula("(NO₂C₆H₄)₂O")
        .color(0xFFFF8F)
        .iconSet(GTMaterialIconSet.ROUGH) 
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('44oda')
        .gas()
        .formula("C₁₂H₁₂N₂O")
        .color(0xFFDEAD)
        .iconSet(GTMaterialIconSet.ROUGH) 
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('pdc44o')
        .gas()
        .formula("C₁₂H₁₂N₂O · C₁₀H₂O₆")
        .color(0xF3E5AB)
        .iconSet(GTMaterialIconSet.ROUGH) 
        .flags(GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

    event.create('kapton')
        .ingot()
        .formula("C₂₂H₁₀N₂O₅")
        .color(0xFFBF00)
        .iconSet(GTMaterialIconSet.ROUGH) 
        .flags(GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.DISABLE_MATERIAL_RECIPES)

         //₀ ₁ ₂ ₃ ₄ ₅ ₆ ₇ ₈ ₉
 
});